TodoItem.create!(title: "Buy a horse")
TodoItem.create!(title: "Kill santa")
TodoItem.create!(title: "Hijak a plane")
TodoItem.create!(title: "Begin potty training")
TodoItem.create!(title: "Go to the dentist")
TodoItem.create!(title: "Drive to England")
TodoItem.create!(title: "Burn a cristmas goat")